# Generated by Django 3.2.7 on 2021-09-06 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choise',
            new_name='Choice',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_Text',
            new_name='question_text',
        ),
    ]
